// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace AudiometryBinaryClassificationML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public float Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public string Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public string Col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public string Col3 { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public string Col4 { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public string Col5 { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public string Col6 { get; set; }


        [ColumnName("col7"), LoadColumn(7)]
        public string Col7 { get; set; }


        [ColumnName("col8"), LoadColumn(8)]
        public string Col8 { get; set; }


        [ColumnName("col9"), LoadColumn(9)]
        public string Col9 { get; set; }


        [ColumnName("col10"), LoadColumn(10)]
        public string Col10 { get; set; }


        [ColumnName("col11"), LoadColumn(11)]
        public string Col11 { get; set; }


        [ColumnName("col12"), LoadColumn(12)]
        public string Col12 { get; set; }


        [ColumnName("col13"), LoadColumn(13)]
        public string Col13 { get; set; }


        [ColumnName("col14"), LoadColumn(14)]
        public string Col14 { get; set; }


        [ColumnName("col15"), LoadColumn(15)]
        public string Col15 { get; set; }


        [ColumnName("col16"), LoadColumn(16)]
        public string Col16 { get; set; }


        [ColumnName("col17"), LoadColumn(17)]
        public string Col17 { get; set; }


        [ColumnName("col18"), LoadColumn(18)]
        public string Col18 { get; set; }


        [ColumnName("col19"), LoadColumn(19)]
        public string Col19 { get; set; }


        [ColumnName("col20"), LoadColumn(20)]
        public string Col20 { get; set; }


        [ColumnName("col21"), LoadColumn(21)]
        public string Col21 { get; set; }


        [ColumnName("col22"), LoadColumn(22)]
        public string Col22 { get; set; }


        [ColumnName("col23"), LoadColumn(23)]
        public string Col23 { get; set; }


        [ColumnName("col24"), LoadColumn(24)]
        public string Col24 { get; set; }


        [ColumnName("col25"), LoadColumn(25)]
        public string Col25 { get; set; }


    }
}
